In [ ]:
remotes::install_github('saezlab/liana#174')

In [1]:
library(liana)
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
op_resource <- liana::generate_homologs(
                op_resource = liana::select_resource('Consensus')[[1]],
                target_organism = 10090,
                .missing_fun = NULL,
                symbols_dict = NULL,
                columns = c("source_genesymbol", "target_genesymbol"),
            )

Entries without homologs:
LGALS9; PODXL; ADGRB1; HLA-B; HLA-DQA2; HLA-DRB1; HLA-DPB1; MELTF; HLA-C; HLA-DRB4; CD99; PLA2G2A; CD58; HLA-DPA1; CEACAM8; ICAM3; CEACAM6; TNFSF9; HLA-DRB3; NRG1; BST2; MADCAM1; NECTIN1; MICA; RAET1L; NCR3LG1; RAET1G; JAML; NLGN4X; RAET1E; NECTIN2; EDA; HAVCR1; NECTIN4; ULBP3; ULBP2; NRXN3; NECTIN3; SIRPG; CLEC2D; HHLA2; DSPP; IGHG1; IGLC1; IFNL4; CCN1; CXCL11; DEFB4B; CCL16; VEGFD; CCN4; GH1; GH2; CALCA; GCG; IFNA1; IFNA2; IFNA10; IFNA7; IFNA21; IFNA5; IFNA14; IFNA17; APOC3; ORM1; PPBP; RLN2; IFNW1; IFNA6; IFNA16; HLA-DQB2; LPA; IL3; CXCL1; SCT; APELA; CSH1; CSH2; CGB8; SLURP2; CXCL8; CCL3; PF4V1; MLN; MUC1; CCL3L1; NPPB; TCN1; ANOS1; IL32; CCN2; IFNA8; BMP8B; CXCL5; CCN3; CCL23; CCL18; DEFB1; CCL8; CCL7; S100A12; DEFB103A; CXCL9; FCN2; CCL14; CCL15; ERFE; SIRPB2; IL31; IGFL1; IGFL2; VSTM1; ALKAL2; ALKAL1; TAC4; IFNL1; IFNL2; DEFB106B; CCL4L1; PRG4; TAFA4; COL21A1; AMELX; SPX; LACRT; IL26; IL37; XCL2; COL17A1; CCL26; CLEC2B; HMGB1; LCN1; CD24; AFDN; GNRH2; GZMB; HRG; C4BPA; ZG16B; CPAMD8; SFTPA2; PTMA; CEACAM5; CD52; CALM1; CALM2; CALM3; PI3; CCN6; CRISP3; APOC1; PSG9; MXRA5; PSG4; CNMD; PSG6; PSG5; PSG7; TREML4; MAML2; TNFRSF6B; PTPRD; VSIR; CD8B2; LILRA1; KIR2DL3; KIR3DL1; KIR3DL2; LILRB2; LILRB1; FPR3; KIR2DL1; CR1; ADGRE5; ADGRE2; KIR2DL2; KIR2DS4; KIR2DS1; LILRA3; KLRC2; KLRC3; KLRK1; KIR2DL4; KIR3DS1; PVR; ADGRG5; NCR3; TNFRSF10B; TNFRSF10D; CD1A; ADGRL1; LILRA4; SIGLEC5; TMIGD2; ACKR1; ADGRV1; NPY4R; NPY6R; FCRL4; ADGRL4; NPTN; MLNR; MCHR2; CD33; GPR42; ADGRG3; NPBWR2; OR1G1; KLRF1; KLRF2; TNFRSF10C; CMKLR2; NCR2; HJV; GPIHBP1; ADGRG1; CD1B; BEX3; ATP5F1B; IFITM1; HTR1E; PLPP6; RACK1; IZUMO1R; BTN3A3; CD1C; ADGRA2; SIGLEC6; MPIG6B; BTN3A2; SIGLEC7; LVRN; MILR1; TMIGD3

One-to-many homolog matches: C4A; C4B; CCL27; CD200R1L; CD55; CEACAM1; CLEC10A; CSF2RB; DSG1; ENO1; GSTP1; HLA-DMB; HLA-E; HLA-F; IFNL3; IL11RA; IL22; KIR3DL3; KLRB1; KNG1; LILRB4; LYZ; MRGPRX2; PILRB; PRND; PRSS3; RNASE2; SAA1; SERPINA1

In [3]:
op_resource

     source_genesymbol target_genesymbol source target
1    Dll1              Notch1            O00548 P46531
2    Dll1              Notch2            O00548 Q04721
3    Dll1              Notch4            O00548 Q99466
4    Dll1              Notch3            O00548 Q9UM47
5    Nrg2              Erbb2_Erbb3       O14511 COMPLEX:P04626_P21860
6    Nrg2              Erbb2_Erbb4       O14511 COMPLEX:P04626_Q15303
7    Adam10            Tspan15           O14672 O95858
8    Adam10            Tspan12           O14672 O95859
9    Adam10            Met               O14672 P08581
10   Adam10            Il6ra             O14672 P08887
11   Adam10            Cd44              O14672 P16070
12   Adam10            Epha3             O14672 P29320
13   Adam10            Axl               O14672 P30530
14   Adam10            Notch1            O14672 P46531
15   Adam10            Notch2            O14672 Q04721
16   Adam10            Nrcam             O14672 Q92823
17   Adam10            Tspan17           O14672 Q96FV3
18   Adam10            Tspan10           O14672 Q9H1Z9
19   Adam10            Trem2             O14672 Q9NZC2
20   Tnfsf11           Tnfrsf11b         O14788 O00300
21   Tnfsf11           Lgr4              O14788 Q9BXB1
22   Tnfsf11           Tnfrsf11a         O14788 Q9Y6Q6
23   Ereg              Egfr_Erbb2        O14944 COMPLEX:P00533_P04626
24   Ereg              Erbb2_Erbb4       O14944 COMPLEX:P04626_Q15303
25   Ereg              Erbb3             O14944 P21860
26   Adam12            Itgb1             O43184 P05556
27   Adam12            Itga9             O43184 Q13797
28   Tnfsf12           Tnfrsf8           O43508 P28908
29   Tnfsf12           Cd163             O43508 Q86VB7
30   Tnfsf12           Tnfrsf25          O43508 Q93038
⋮    ⋮                 ⋮                 ⋮      ⋮
3969 Try5              F2rl2             P35030 O00254
3970 Try4              F2rl3             P35030 Q96RI0
3971 Try5              F2rl3             P35030 Q96RI0
3972 Try4              Pard3             P35030 Q8TEW0
3973 Try5              Pard3             P35030 Q8TEW0
3974 Ear11             Tlr2              P10153 O60603
3975 Ear5              Tlr2              P10153 O60603
3976 Saa1              Adra2a            P0DJI8 P08913
3977 Saa2              Adra2a            P0DJI8 P08913
3978 Saa1              Cd36              P0DJI8 P16671
3979 Saa2              Cd36              P0DJI8 P16671
3980 Saa1              Fpr1              P0DJI8 P21462
3981 Saa2              Fpr1              P0DJI8 P21462
3982 Saa1              Fpr2              P0DJI8 P25090
3983 Saa2              Fpr2              P0DJI8 P25090
3984 Saa1              Grm7              P0DJI8 Q14831
3985 Saa2              Grm7              P0DJI8 Q14831
3986 Saa1              Mtnr1a            P0DJI8 P48039
3987 Saa2              Mtnr1a            P0DJI8 P48039
3988 Saa1              Scarb1            P0DJI8 Q8WTV0
3989 Saa2              Scarb1            P0DJI8 Q8WTV0
3990 Saa1              Tlr2              P0DJI8 O60603
3991 Saa2              Tlr2              P0DJI8 O60603
3992 Sele              Ceacam1           P16581 P13688
3993 Sele              Ceacam2           P16581 P13688
3994 Serpina1a         Lrp1              P01009 Q07954
3995 Serpina1b         Lrp1              P01009 Q07954
3996 Serpina1c         Lrp1              P01009 Q07954
3997 Serpina1d         Lrp1              P01009 Q07954
3998 Serpina1e         Lrp1              P01009 Q07954
     category_intercell_source
1    cell_surface_ligand
2    cell_surface_ligand
3    cell_surface_ligand
4    cell_surface_ligand
5    cell_surface_ligand
6    cell_surface_ligand
7    cell_surface_ligand
8    cell_surface_ligand
9    cell_surface_ligand
10   cell_surface_ligand
11   cell_surface_ligand
12   cell_surface_ligand
13   cell_surface_ligand
14   cell_surface_ligand
15   cell_surface_ligand
16   cell_surface_ligand
17   cell_surface_ligand
18   cell_surface_ligand
19   cell_surface_ligand
20   cell_surface_ligand
21   cell_surface_ligand
22   cell_surface_ligand
23   cell_surface_ligand
24   cell_surface_ligand
25   cell_surface_ligand
26   cell_surface_ligand
27   cell_surface_ligand
28   cell_surface_ligand
29   cell_surface_ligand
30   cell_surface_ligand
⋮    ⋮
3969 ligand
3970 ligand
3971 ligand
3972 ligand
3973 ligand
3974
3975
3976 ligand
3977 ligand
3978 ligand
3979 ligand
3980 ligand
3981 ligand
3982 ligand
3983 ligand
3984 ligand
3985 ligand
3986 ligand
3987 ligand
3988 ligand
3989 ligand
3990 ligand
3991 ligand
3992 cell_surface_ligand
3993 cell_surface_ligand
3994
3995
3996
3997
3998
     database_intercell_source
1    connectomeDB2020;CellChatDB;CellPhoneDB
2    connectomeDB2020;CellChatDB;CellPhoneDB
3    connectomeDB2020;CellChatDB;CellPhoneDB
4    connectomeDB2020;CellChatDB;CellPhoneDB
5    CellPhoneDB
6    CellPhoneDB
7    connectomeDB2020
8    connectomeDB2020
9    connectomeDB2020
10   connectomeDB2020
11   connectomeDB2020
12   connectomeDB2020
13   connectomeDB2020
14   connectomeDB2020
15   connectomeDB2020
16   connectomeDB2020
17   connectomeDB2020
18   connectomeDB2020
19   connectomeDB2020
20   connectomeDB2020
21   connectomeDB2020
22   connectomeDB2020
23   CellPhoneDB
24   CellPhoneDB
25   CellPhoneDB
26   connectomeDB2020
27   connectomeDB2020
28   connectomeDB2020;CellPhoneDB
29   connectomeDB2020;CellPhoneDB
30   connectomeDB2020;CellPhoneDB
⋮    ⋮
3969 CellChatDB
3970 CellChatDB
3971 CellChatDB
3972 CellChatDB
3973 CellChatDB
3974
3975
3976 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3977 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3978 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3979 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3980 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3981 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3982 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3983 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3984 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3985 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3986 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3987 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3988 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3989 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3990 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3991 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3992 connectomeDB2020;CellChatDB;CellPhoneDB
3993 connectomeDB2020;CellChatDB;CellPhoneDB
3994
3995
3996
3997
3998
     category_intercell_target
1    receptor
2    receptor
3    receptor
4    receptor
5    receptor
6    receptor
7    receptor
8    receptor
9    receptor
10   receptor
11   receptor
12   receptor
13   receptor
14   receptor
15   receptor
16   receptor
17   receptor
18   receptor
19   receptor
20   receptor
21   receptor
22   receptor
23   receptor
24   receptor
25   receptor
26   receptor
27   receptor
28   receptor
29   receptor
30   receptor
⋮    ⋮
3969 receptor
3970 receptor
3971 receptor
3972 receptor
3973 receptor
3974
3975
3976 receptor
3977 receptor
3978 receptor
3979 receptor
3980 receptor
3981 receptor
3982 receptor
3983 receptor
3984 receptor
3985 receptor
3986 receptor
3987 receptor
3988 receptor
3989 receptor
3990 receptor
3991 receptor
3992 receptor
3993 receptor
3994
3995
3996
3997
3998
     database_intercell_target
1    connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
2    connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3    connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
4    connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
5    connectomeDB2020;CellChatDB;CellTalkDB
6    connectomeDB2020;CellChatDB;CellTalkDB
7    CellTalkDB
8    CellTalkDB
9    connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
10   connectomeDB2020;CellPhoneDB;ICELLNET;CellTalkDB
11   connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
12   connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
13   connectomeDB2020;CellPhoneDB;CellChatDB;CellTalkDB
14   connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
15   connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
16   connectomeDB2020;CellChatDB;CellTalkDB
17   CellTalkDB
18   CellTalkDB
19   connectomeDB2020;CellPhoneDB;CellTalkDB
20   connectomeDB2020;ICELLNET;CellChatDB;CellTalkDB
21   connectomeDB2020;CellPhoneDB;ICELLNET;CellTalkDB
22   connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
23   connectomeDB2020;CellChatDB;CellTalkDB
24   connectomeDB2020;CellChatDB;CellTalkDB
25   connectomeDB2020;CellPhoneDB;CellChatDB;CellTalkDB
26   connectomeDB2020;CellPhoneDB;ICELLNET;CellTalkDB
27   connectomeDB2020;CellPhoneDB;ICELLNET;CellTalkDB
28   connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
29   connectomeDB2020;CellTalkDB
30   connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
⋮    ⋮
3969 connectomeDB2020;CellChatDB;CellTalkDB
3970 connectomeDB2020;CellChatDB;CellTalkDB
3971 connectomeDB2020;CellChatDB;CellTalkDB
3972 CellChatDB
3973 CellChatDB
3974
3975
3976 connectomeDB2020;CellTalkDB
3977 connectomeDB2020;CellTalkDB
3978 connectomeDB2020;CellPhoneDB;CellChatDB;CellTalkDB
3979 connectomeDB2020;CellPhoneDB;CellChatDB;CellTalkDB
3980 connectomeDB2020;CellPhoneDB;CellChatDB;CellTalkDB
3981 connectomeDB2020;CellPhoneDB;CellChatDB;CellTalkDB
3982 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3983 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3984 CellTalkDB
3985 CellTalkDB
3986 connectomeDB2020;CellTalkDB
3987 connectomeDB2020;CellTalkDB
3988 connectomeDB2020;CellTalkDB
3989 connectomeDB2020;CellTalkDB
3990 connectomeDB2020;CellTalkDB
3991 connectomeDB2020;CellTalkDB
3992 connectomeDB2020;CellChatDB
3993 connectomeDB2020;CellChatDB
3994
3995
3996
3997
3998
     sources
1    Baccin2019;CellCall;CellChatDB;CellPhoneDB;CellPhoneDB_Cellinker;CellTalkDB;Cellinker;DLRP_Cellinker;DLRP_talklr;EMBRACE;Fantom5_LRdb;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;ICELLNET;KEGG-MEDICUS;Kirouac2010;LRdb;NetPath;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;SPIKE;STRING_talklr;UniProt_LRdb;Wang;connectomeDB2020;iTALK;talklr
2    Baccin2019;BioGRID;CellCall;CellChatDB;CellPhoneDB;CellPhoneDB_Cellinker;CellTalkDB;Cellinker;DLRP_Cellinker;DLRP_talklr;Fantom5_LRdb;HPRD;HPRD_LRdb;HPRD_talklr;ICELLNET;KEGG-MEDICUS;LRdb;NetPath;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;STRING_talklr;UniProt_LRdb;Wang;connectomeDB2020;iTALK;talklr
3    CellCall;CellChatDB;CellPhoneDB;CellPhoneDB_Cellinker;CellTalkDB;Cellinker;DLRP_Cellinker;DLRP_talklr;EMBRACE;KEGG-MEDICUS;LRdb;UniProt_LRdb;Wang;connectomeDB2020;iTALK;talklr
4    Baccin2019;CancerCellMap;CellCall;CellChatDB;CellPhoneDB;CellPhoneDB_Cellinker;CellTalkDB;Cellinker;DLRP_Cellinker;DLRP_talklr;EMBRACE;Fantom5_LRdb;HPRD;HPRD_LRdb;HPRD_talklr;ICELLNET;KEGG-MEDICUS;LRdb;NetPath;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;STRING_talklr;UniProt_LRdb;Wang;Wojtowicz2020;connectomeDB2020;iTALK;talklr
5    CellChatDB;Cellinker;Guide2Pharma_Cellinker;HPMR_Cellinker
6    CellChatDB;Cellinker;Guide2Pharma_Cellinker;HPMR_Cellinker
7    CellTalkDB;Cellinker;IntAct
8    CellTalkDB
9    CellTalkDB
10   CellTalkDB
11   CellTalkDB;SIGNOR
12   Baccin2019;CellTalkDB;EMBRACE;Fantom5_LRdb;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;STRING_talklr;connectomeDB2020;iTALK;talklr
13   CellTalkDB;EMBRACE;Fantom5_LRdb;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;iTALK;talklr
14   ACSN;CellTalkDB;Cellinker;LRdb;SIGNOR;Wang
15   ACSN;CellTalkDB;SignaLink3;Wang
16   CellTalkDB
17   CellTalkDB;Cellinker
18   CellTalkDB;Cellinker
19   CellTalkDB
20   Baccin2019;CellChatDB;CellPhoneDB;CellTalkDB;Cellinker;DLRP_Cellinker;DLRP_talklr;EMBRACE;Fantom5_LRdb;HPMR;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;ICELLNET;IntAct;LRdb;NetPath;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;STRING_talklr;UniProt_LRdb;Wang;connectomeDB2020;iTALK;talklr
21   CellTalkDB
22   Baccin2019;CellCall;CellChatDB;CellPhoneDB;CellTalkDB;Cellinker;DLRP_Cellinker;DLRP_talklr;EMBRACE;Fantom5_LRdb;Guide2Pharma;Guide2Pharma_Cellinker;Guide2Pharma_LRdb;Guide2Pharma_talklr;HPMR;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;ICELLNET;IntAct;LRdb;NetPath;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;UniProt_LRdb;Wang;connectomeDB2020;iTALK;scConnect;talklr
23   CellChatDB;Cellinker;DLRP_Cellinker;Guide2Pharma_Cellinker;HPMR_Cellinker
24   CellChatDB;Cellinker;DLRP_Cellinker;Guide2Pharma_Cellinker
25   CellCall;CellTalkDB;Fantom5_LRdb;LRdb;SIGNOR;STRING_talklr;iTALK;talklr
26   Adhesome;CellTalkDB;EMBRACE;Fantom5_LRdb;HPMR_LRdb;HPMR_talklr;LRdb;Ramilowski2015;STRING_talklr;Wang;connectomeDB2020;iTALK;talklr
27   CellTalkDB;EMBRACE;Fantom5_LRdb;HPMR_LRdb;HPMR_talklr;LRdb;Ramilowski2015;STRING_talklr;Wang;connectomeDB2020;iTALK;talklr
28   CellTalkDB;LRdb;UniProt_LRdb
29   NetPath;connectomeDB2020
30   CellPhoneDB;CellTalkDB;Cellinker;DLRP_Cellinker;DLRP_talklr;Fantom5_LRdb;HPRD;HPRD_LRdb;HPRD_talklr;I2D_CellPhoneDB;LRdb;NetPath;Ramilowski2015;UniProt_LRdb;Wang;iTALK;talklr
⋮    ⋮
3969 CellChatDB;Wang
3970 CellChatDB;Wang
3971 CellChatDB;Wang
3972 CellChatDB;Wang
3973 CellChatDB;Wang
3974 CellTalkDB;Cellinker;Fantom5_LRdb;LRdb;Ramilowski2015;Wang;connectomeDB2020;iTALK;talklr
3975 CellTalkDB;Cellinker;Fantom5_LRdb;LRdb;Ramilowski2015;Wang;connectomeDB2020;iTALK;talklr
3976 CellTalkDB;LRdb;Reactome_LRdb
3977 CellTalkDB;LRdb;Reactome_LRdb
3978 connectomeDB2020
3979 connectomeDB2020
3980 Baccin2019;CellTalkDB;Cellinker;Fantom5_LRdb;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;iTALK;talklr
3981 Baccin2019;CellTalkDB;Cellinker;Fantom5_LRdb;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;iTALK;talklr
3982 Baccin2019;CellChatDB;CellPhoneDB;CellTalkDB;Cellinker;Fantom5_LRdb;Guide2Pharma;Guide2Pharma_CellPhoneDB;Guide2Pharma_Cellinker;Guide2Pharma_LRdb;Guide2Pharma_talklr;ICELLNET;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;Wang;connectomeDB2020;iTALK;scConnect;talklr
3983 Baccin2019;CellChatDB;CellPhoneDB;CellTalkDB;Cellinker;Fantom5_LRdb;Guide2Pharma;Guide2Pharma_CellPhoneDB;Guide2Pharma_Cellinker;Guide2Pharma_LRdb;Guide2Pharma_talklr;ICELLNET;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;Wang;connectomeDB2020;iTALK;scConnect;talklr
3984 CellTalkDB;LRdb;Reactome_LRdb
3985 CellTalkDB;LRdb;Reactome_LRdb
3986 CellTalkDB;LRdb;Reactome_LRdb
3987 CellTalkDB;LRdb;Reactome_LRdb
3988 CellTalkDB;Fantom5_LRdb;LRdb;STRING_talklr;Wang;iTALK;talklr
3989 CellTalkDB;Fantom5_LRdb;LRdb;STRING_talklr;Wang;iTALK;talklr
3990 CellTalkDB;Wang
3991 CellTalkDB;Wang
3992 CellChatDB;CellPhoneDB;CellPhoneDB_Cellinker;Cellinker
3993 CellChatDB;CellPhoneDB;CellPhoneDB_Cellinker;Cellinker
3994 Baccin2019;CellTalkDB;Cellinker;Fantom5_LRdb;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;Wang;connectomeDB2020;iTALK;talklr
3995 Baccin2019;CellTalkDB;Cellinker;Fantom5_LRdb;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;Wang;connectomeDB2020;iTALK;talklr
3996 Baccin2019;CellTalkDB;Cellinker;Fantom5_LRdb;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;Wang;connectomeDB2020;iTALK;talklr
3997 Baccin2019;CellTalkDB;Cellinker;Fantom5_LRdb;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;Wang;connectomeDB2020;iTALK;talklr
3998 Baccin2019;CellTalkDB;Cellinker;Fantom5_LRdb;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;Wang;connectomeDB2020;iTALK;talklr
     references
1    Baccin2019:1006133;Baccin2019:98194281;CellChatDB:22353464;CellPhoneDB:22353464;CellTalkDB:22353464;Cellinker:11006133;Cellinker:22353464;Cellinker:9819428;HPRD:11006133;ICELLNET:21685328;LRdb:11;LRdb:9819428;NetPath:11006133;SIGNOR:16140393;SPIKE:11006133;SPIKE:17537801;connectomeDB2020:11006133;connectomeDB2020:9819428
2    Baccin2019:10958687;BioGRID:9244302;CellChatDB:22353464;CellPhoneDB:22353464;CellTalkDB:10958687;Cellinker:10958687;Cellinker:22353464;HPRD:10958687;ICELLNET:21685328;LRdb:10958687;NetPath:10958687;SIGNOR:23111325;connectomeDB2020:10958687
3    CellChatDB:22353464;CellPhoneDB:22353464;CellTalkDB:22353464;Cellinker:22353464;Cellinker:29910816;connectomeDB2020:22353464
4    Baccin2019:11006133;Baccin2019:12482954;CancerCellMap:11006133;CellChatDB:22353464;CellPhoneDB:22353464;CellTalkDB:12482954;Cellinker:11006133;Cellinker:12482954;Cellinker:22353464;HPRD:11006133;HPRD:12482954;ICELLNET:21685328;LRdb:11;LRdb:12482954;NetPath:11006133;SIGNOR:11006133;connectomeDB2020:11006133;connectomeDB2020:12482954
5    Cellinker:9168114;Cellinker:9168115
6    Cellinker:9168114;Cellinker:9168115
7    CellTalkDB:23035126;Cellinker:23035126;IntAct:23091066;IntAct:26686862
8    CellTalkDB:19587294
9    CellTalkDB:22689693
10   CellTalkDB:21454673
11   CellTalkDB:18971959;SIGNOR:26284334
12   Baccin2019:16239146;CellTalkDB:16239146;HPRD:16239146;LRdb:16239146;connectomeDB2020:16239146
13   CellTalkDB:7822279;HPRD:16227584;HPRD:7822279;LRdb:7822279
14   ACSN:19601831;ACSN:19704010;ACSN:19726682;CellTalkDB:22399336;Cellinker:22399336;LRdb:22399336;SIGNOR:28624438
15   ACSN:19601831;ACSN:19704010;ACSN:19726682;CellTalkDB:24842903;SignaLink3:10423016;SignaLink3:23331499
16   CellTalkDB:30833305
17   CellTalkDB:23035126;Cellinker:23035126
18   CellTalkDB:28687716;Cellinker:23035126
19   CellTalkDB:28923481
20   Baccin2019:11733492;Baccin2019:12221720;Baccin2019:9520411;Baccin2019:9568710;CellTalkDB:11733492;Cellinker:11733492;Cellinker:12221720;Cellinker:9520411;Cellinker:9568710;HPMR:9568710;HPRD:12221720;HPRD:9520411;ICELLNET:11239407;IntAct:22664871;LRdb:11733492;LRdb:12221720;LRdb:9520411;LRdb:9568710;NetPath:14741739;NetPath:9568710;SIGNOR:11733492;connectomeDB2020:11733492;connectomeDB2020:12221720;connectomeDB2020:9520411;connectomeDB2020:9568710
21   CellTalkDB:27064449
22   Baccin2019:11581298;Baccin2019:9367155;CellTalkDB:11581298;Cellinker:11581298;Cellinker:9367155;HPMR:11581298;HPMR:15110169;HPRD:9367155;ICELLNET:11239407;IntAct:23333834;LRdb:11581298;LRdb:94;NetPath:14741739;NetPath:20483727;NetPath:9520411;SIGNOR:12897775;connectomeDB2020:11581298;connectomeDB2020:9367155
23   Cellinker:8626392;Cellinker:9419975
24   Cellinker:9419975
25   CellTalkDB:32196115;SIGNOR:16829981;SIGNOR:22891299
26   Adhesome:15242759;CellTalkDB:10944520;LRdb:10944520;connectomeDB2020:10944520
27   CellTalkDB:10944520;LRdb:10944520;connectomeDB2020:10944520
28   CellTalkDB:32196115
29   NetPath:17548657;connectomeDB2020:19473660
30   CellTalkDB:11094155;Cellinker:11094155;HPRD:11094155;LRdb:11094155;NetPath:11094155
⋮    ⋮
3969
3970
3971
3972
3973
3974 CellTalkDB:18195069;Cellinker:18195069;LRdb:18195069;Ramilowski2015:18195069;connectomeDB2020:18195069;talklr:18195069
3975 CellTalkDB:18195069;Cellinker:18195069;LRdb:18195069;Ramilowski2015:18195069;connectomeDB2020:18195069;talklr:18195069
3976 CellTalkDB:32196115
3977 CellTalkDB:32196115
3978 connectomeDB2020:20075072
3979 connectomeDB2020:20075072
3980 Baccin2019:10753626;CellTalkDB:10753626;Cellinker:10753626;HPRD:10753626;LRdb:10753626
3981 Baccin2019:10753626;CellTalkDB:10753626;Cellinker:10753626;HPRD:10753626;LRdb:10753626
3982 Baccin2019:9892621;CellChatDB:22610094;CellTalkDB:9892621;Cellinker:22610094;Cellinker:9892621;Guide2Pharma:9892621;ICELLNET:26130702;LRdb:9892621;connectomeDB2020:9892621;scConnect:9892621
3983 Baccin2019:9892621;CellChatDB:22610094;CellTalkDB:9892621;Cellinker:22610094;Cellinker:9892621;Guide2Pharma:9892621;ICELLNET:26130702;LRdb:9892621;connectomeDB2020:9892621;scConnect:9892621

In [4]:
mutate(
    op_resource,
    ligand_genesymbol = source_genesymbol,
    receptor_genesymbol = target_genesymbol
)

     source_genesymbol target_genesymbol source target
1    Dll1              Notch1            O00548 P46531
2    Dll1              Notch2            O00548 Q04721
3    Dll1              Notch4            O00548 Q99466
4    Dll1              Notch3            O00548 Q9UM47
5    Nrg2              Erbb2_Erbb3       O14511 COMPLEX:P04626_P21860
6    Nrg2              Erbb2_Erbb4       O14511 COMPLEX:P04626_Q15303
7    Adam10            Tspan15           O14672 O95858
8    Adam10            Tspan12           O14672 O95859
9    Adam10            Met               O14672 P08581
10   Adam10            Il6ra             O14672 P08887
11   Adam10            Cd44              O14672 P16070
12   Adam10            Epha3             O14672 P29320
13   Adam10            Axl               O14672 P30530
14   Adam10            Notch1            O14672 P46531
15   Adam10            Notch2            O14672 Q04721
16   Adam10            Nrcam             O14672 Q92823
17   Adam10            Tspan17           O14672 Q96FV3
18   Adam10            Tspan10           O14672 Q9H1Z9
19   Adam10            Trem2             O14672 Q9NZC2
20   Tnfsf11           Tnfrsf11b         O14788 O00300
21   Tnfsf11           Lgr4              O14788 Q9BXB1
22   Tnfsf11           Tnfrsf11a         O14788 Q9Y6Q6
23   Ereg              Egfr_Erbb2        O14944 COMPLEX:P00533_P04626
24   Ereg              Erbb2_Erbb4       O14944 COMPLEX:P04626_Q15303
25   Ereg              Erbb3             O14944 P21860
26   Adam12            Itgb1             O43184 P05556
27   Adam12            Itga9             O43184 Q13797
28   Tnfsf12           Tnfrsf8           O43508 P28908
29   Tnfsf12           Cd163             O43508 Q86VB7
30   Tnfsf12           Tnfrsf25          O43508 Q93038
⋮    ⋮                 ⋮                 ⋮      ⋮
3969 Try5              F2rl2             P35030 O00254
3970 Try4              F2rl3             P35030 Q96RI0
3971 Try5              F2rl3             P35030 Q96RI0
3972 Try4              Pard3             P35030 Q8TEW0
3973 Try5              Pard3             P35030 Q8TEW0
3974 Ear11             Tlr2              P10153 O60603
3975 Ear5              Tlr2              P10153 O60603
3976 Saa1              Adra2a            P0DJI8 P08913
3977 Saa2              Adra2a            P0DJI8 P08913
3978 Saa1              Cd36              P0DJI8 P16671
3979 Saa2              Cd36              P0DJI8 P16671
3980 Saa1              Fpr1              P0DJI8 P21462
3981 Saa2              Fpr1              P0DJI8 P21462
3982 Saa1              Fpr2              P0DJI8 P25090
3983 Saa2              Fpr2              P0DJI8 P25090
3984 Saa1              Grm7              P0DJI8 Q14831
3985 Saa2              Grm7              P0DJI8 Q14831
3986 Saa1              Mtnr1a            P0DJI8 P48039
3987 Saa2              Mtnr1a            P0DJI8 P48039
3988 Saa1              Scarb1            P0DJI8 Q8WTV0
3989 Saa2              Scarb1            P0DJI8 Q8WTV0
3990 Saa1              Tlr2              P0DJI8 O60603
3991 Saa2              Tlr2              P0DJI8 O60603
3992 Sele              Ceacam1           P16581 P13688
3993 Sele              Ceacam2           P16581 P13688
3994 Serpina1a         Lrp1              P01009 Q07954
3995 Serpina1b         Lrp1              P01009 Q07954
3996 Serpina1c         Lrp1              P01009 Q07954
3997 Serpina1d         Lrp1              P01009 Q07954
3998 Serpina1e         Lrp1              P01009 Q07954
     category_intercell_source
1    cell_surface_ligand
2    cell_surface_ligand
3    cell_surface_ligand
4    cell_surface_ligand
5    cell_surface_ligand
6    cell_surface_ligand
7    cell_surface_ligand
8    cell_surface_ligand
9    cell_surface_ligand
10   cell_surface_ligand
11   cell_surface_ligand
12   cell_surface_ligand
13   cell_surface_ligand
14   cell_surface_ligand
15   cell_surface_ligand
16   cell_surface_ligand
17   cell_surface_ligand
18   cell_surface_ligand
19   cell_surface_ligand
20   cell_surface_ligand
21   cell_surface_ligand
22   cell_surface_ligand
23   cell_surface_ligand
24   cell_surface_ligand
25   cell_surface_ligand
26   cell_surface_ligand
27   cell_surface_ligand
28   cell_surface_ligand
29   cell_surface_ligand
30   cell_surface_ligand
⋮    ⋮
3969 ligand
3970 ligand
3971 ligand
3972 ligand
3973 ligand
3974
3975
3976 ligand
3977 ligand
3978 ligand
3979 ligand
3980 ligand
3981 ligand
3982 ligand
3983 ligand
3984 ligand
3985 ligand
3986 ligand
3987 ligand
3988 ligand
3989 ligand
3990 ligand
3991 ligand
3992 cell_surface_ligand
3993 cell_surface_ligand
3994
3995
3996
3997
3998
     database_intercell_source
1    connectomeDB2020;CellChatDB;CellPhoneDB
2    connectomeDB2020;CellChatDB;CellPhoneDB
3    connectomeDB2020;CellChatDB;CellPhoneDB
4    connectomeDB2020;CellChatDB;CellPhoneDB
5    CellPhoneDB
6    CellPhoneDB
7    connectomeDB2020
8    connectomeDB2020
9    connectomeDB2020
10   connectomeDB2020
11   connectomeDB2020
12   connectomeDB2020
13   connectomeDB2020
14   connectomeDB2020
15   connectomeDB2020
16   connectomeDB2020
17   connectomeDB2020
18   connectomeDB2020
19   connectomeDB2020
20   connectomeDB2020
21   connectomeDB2020
22   connectomeDB2020
23   CellPhoneDB
24   CellPhoneDB
25   CellPhoneDB
26   connectomeDB2020
27   connectomeDB2020
28   connectomeDB2020;CellPhoneDB
29   connectomeDB2020;CellPhoneDB
30   connectomeDB2020;CellPhoneDB
⋮    ⋮
3969 CellChatDB
3970 CellChatDB
3971 CellChatDB
3972 CellChatDB
3973 CellChatDB
3974
3975
3976 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3977 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3978 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3979 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3980 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3981 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3982 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3983 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3984 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3985 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3986 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3987 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3988 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3989 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3990 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3991 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3992 connectomeDB2020;CellChatDB;CellPhoneDB
3993 connectomeDB2020;CellChatDB;CellPhoneDB
3994
3995
3996
3997
3998
     category_intercell_target
1    receptor
2    receptor
3    receptor
4    receptor
5    receptor
6    receptor
7    receptor
8    receptor
9    receptor
10   receptor
11   receptor
12   receptor
13   receptor
14   receptor
15   receptor
16   receptor
17   receptor
18   receptor
19   receptor
20   receptor
21   receptor
22   receptor
23   receptor
24   receptor
25   receptor
26   receptor
27   receptor
28   receptor
29   receptor
30   receptor
⋮    ⋮
3969 receptor
3970 receptor
3971 receptor
3972 receptor
3973 receptor
3974
3975
3976 receptor
3977 receptor
3978 receptor
3979 receptor
3980 receptor
3981 receptor
3982 receptor
3983 receptor
3984 receptor
3985 receptor
3986 receptor
3987 receptor
3988 receptor
3989 receptor
3990 receptor
3991 receptor
3992 receptor
3993 receptor
3994
3995
3996
3997
3998
     database_intercell_target
1    connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
2    connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3    connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
4    connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
5    connectomeDB2020;CellChatDB;CellTalkDB
6    connectomeDB2020;CellChatDB;CellTalkDB
7    CellTalkDB
8    CellTalkDB
9    connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
10   connectomeDB2020;CellPhoneDB;ICELLNET;CellTalkDB
11   connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
12   connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
13   connectomeDB2020;CellPhoneDB;CellChatDB;CellTalkDB
14   connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
15   connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
16   connectomeDB2020;CellChatDB;CellTalkDB
17   CellTalkDB
18   CellTalkDB
19   connectomeDB2020;CellPhoneDB;CellTalkDB
20   connectomeDB2020;ICELLNET;CellChatDB;CellTalkDB
21   connectomeDB2020;CellPhoneDB;ICELLNET;CellTalkDB
22   connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
23   connectomeDB2020;CellChatDB;CellTalkDB
24   connectomeDB2020;CellChatDB;CellTalkDB
25   connectomeDB2020;CellPhoneDB;CellChatDB;CellTalkDB
26   connectomeDB2020;CellPhoneDB;ICELLNET;CellTalkDB
27   connectomeDB2020;CellPhoneDB;ICELLNET;CellTalkDB
28   connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
29   connectomeDB2020;CellTalkDB
30   connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
⋮    ⋮
3969 connectomeDB2020;CellChatDB;CellTalkDB
3970 connectomeDB2020;CellChatDB;CellTalkDB
3971 connectomeDB2020;CellChatDB;CellTalkDB
3972 CellChatDB
3973 CellChatDB
3974
3975
3976 connectomeDB2020;CellTalkDB
3977 connectomeDB2020;CellTalkDB
3978 connectomeDB2020;CellPhoneDB;CellChatDB;CellTalkDB
3979 connectomeDB2020;CellPhoneDB;CellChatDB;CellTalkDB
3980 connectomeDB2020;CellPhoneDB;CellChatDB;CellTalkDB
3981 connectomeDB2020;CellPhoneDB;CellChatDB;CellTalkDB
3982 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3983 connectomeDB2020;CellPhoneDB;ICELLNET;CellChatDB;CellTalkDB
3984 CellTalkDB
3985 CellTalkDB
3986 connectomeDB2020;CellTalkDB
3987 connectomeDB2020;CellTalkDB
3988 connectomeDB2020;CellTalkDB
3989 connectomeDB2020;CellTalkDB
3990 connectomeDB2020;CellTalkDB
3991 connectomeDB2020;CellTalkDB
3992 connectomeDB2020;CellChatDB
3993 connectomeDB2020;CellChatDB
3994
3995
3996
3997
3998
     sources
1    Baccin2019;CellCall;CellChatDB;CellPhoneDB;CellPhoneDB_Cellinker;CellTalkDB;Cellinker;DLRP_Cellinker;DLRP_talklr;EMBRACE;Fantom5_LRdb;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;ICELLNET;KEGG-MEDICUS;Kirouac2010;LRdb;NetPath;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;SPIKE;STRING_talklr;UniProt_LRdb;Wang;connectomeDB2020;iTALK;talklr
2    Baccin2019;BioGRID;CellCall;CellChatDB;CellPhoneDB;CellPhoneDB_Cellinker;CellTalkDB;Cellinker;DLRP_Cellinker;DLRP_talklr;Fantom5_LRdb;HPRD;HPRD_LRdb;HPRD_talklr;ICELLNET;KEGG-MEDICUS;LRdb;NetPath;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;STRING_talklr;UniProt_LRdb;Wang;connectomeDB2020;iTALK;talklr
3    CellCall;CellChatDB;CellPhoneDB;CellPhoneDB_Cellinker;CellTalkDB;Cellinker;DLRP_Cellinker;DLRP_talklr;EMBRACE;KEGG-MEDICUS;LRdb;UniProt_LRdb;Wang;connectomeDB2020;iTALK;talklr
4    Baccin2019;CancerCellMap;CellCall;CellChatDB;CellPhoneDB;CellPhoneDB_Cellinker;CellTalkDB;Cellinker;DLRP_Cellinker;DLRP_talklr;EMBRACE;Fantom5_LRdb;HPRD;HPRD_LRdb;HPRD_talklr;ICELLNET;KEGG-MEDICUS;LRdb;NetPath;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;STRING_talklr;UniProt_LRdb;Wang;Wojtowicz2020;connectomeDB2020;iTALK;talklr
5    CellChatDB;Cellinker;Guide2Pharma_Cellinker;HPMR_Cellinker
6    CellChatDB;Cellinker;Guide2Pharma_Cellinker;HPMR_Cellinker
7    CellTalkDB;Cellinker;IntAct
8    CellTalkDB
9    CellTalkDB
10   CellTalkDB
11   CellTalkDB;SIGNOR
12   Baccin2019;CellTalkDB;EMBRACE;Fantom5_LRdb;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;STRING_talklr;connectomeDB2020;iTALK;talklr
13   CellTalkDB;EMBRACE;Fantom5_LRdb;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;iTALK;talklr
14   ACSN;CellTalkDB;Cellinker;LRdb;SIGNOR;Wang
15   ACSN;CellTalkDB;SignaLink3;Wang
16   CellTalkDB
17   CellTalkDB;Cellinker
18   CellTalkDB;Cellinker
19   CellTalkDB
20   Baccin2019;CellChatDB;CellPhoneDB;CellTalkDB;Cellinker;DLRP_Cellinker;DLRP_talklr;EMBRACE;Fantom5_LRdb;HPMR;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;ICELLNET;IntAct;LRdb;NetPath;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;STRING_talklr;UniProt_LRdb;Wang;connectomeDB2020;iTALK;talklr
21   CellTalkDB
22   Baccin2019;CellCall;CellChatDB;CellPhoneDB;CellTalkDB;Cellinker;DLRP_Cellinker;DLRP_talklr;EMBRACE;Fantom5_LRdb;Guide2Pharma;Guide2Pharma_Cellinker;Guide2Pharma_LRdb;Guide2Pharma_talklr;HPMR;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;ICELLNET;IntAct;LRdb;NetPath;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;UniProt_LRdb;Wang;connectomeDB2020;iTALK;scConnect;talklr
23   CellChatDB;Cellinker;DLRP_Cellinker;Guide2Pharma_Cellinker;HPMR_Cellinker
24   CellChatDB;Cellinker;DLRP_Cellinker;Guide2Pharma_Cellinker
25   CellCall;CellTalkDB;Fantom5_LRdb;LRdb;SIGNOR;STRING_talklr;iTALK;talklr
26   Adhesome;CellTalkDB;EMBRACE;Fantom5_LRdb;HPMR_LRdb;HPMR_talklr;LRdb;Ramilowski2015;STRING_talklr;Wang;connectomeDB2020;iTALK;talklr
27   CellTalkDB;EMBRACE;Fantom5_LRdb;HPMR_LRdb;HPMR_talklr;LRdb;Ramilowski2015;STRING_talklr;Wang;connectomeDB2020;iTALK;talklr
28   CellTalkDB;LRdb;UniProt_LRdb
29   NetPath;connectomeDB2020
30   CellPhoneDB;CellTalkDB;Cellinker;DLRP_Cellinker;DLRP_talklr;Fantom5_LRdb;HPRD;HPRD_LRdb;HPRD_talklr;I2D_CellPhoneDB;LRdb;NetPath;Ramilowski2015;UniProt_LRdb;Wang;iTALK;talklr
⋮    ⋮
3969 CellChatDB;Wang
3970 CellChatDB;Wang
3971 CellChatDB;Wang
3972 CellChatDB;Wang
3973 CellChatDB;Wang
3974 CellTalkDB;Cellinker;Fantom5_LRdb;LRdb;Ramilowski2015;Wang;connectomeDB2020;iTALK;talklr
3975 CellTalkDB;Cellinker;Fantom5_LRdb;LRdb;Ramilowski2015;Wang;connectomeDB2020;iTALK;talklr
3976 CellTalkDB;LRdb;Reactome_LRdb
3977 CellTalkDB;LRdb;Reactome_LRdb
3978 connectomeDB2020
3979 connectomeDB2020
3980 Baccin2019;CellTalkDB;Cellinker;Fantom5_LRdb;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;iTALK;talklr
3981 Baccin2019;CellTalkDB;Cellinker;Fantom5_LRdb;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;iTALK;talklr
3982 Baccin2019;CellChatDB;CellPhoneDB;CellTalkDB;Cellinker;Fantom5_LRdb;Guide2Pharma;Guide2Pharma_CellPhoneDB;Guide2Pharma_Cellinker;Guide2Pharma_LRdb;Guide2Pharma_talklr;ICELLNET;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;Wang;connectomeDB2020;iTALK;scConnect;talklr
3983 Baccin2019;CellChatDB;CellPhoneDB;CellTalkDB;Cellinker;Fantom5_LRdb;Guide2Pharma;Guide2Pharma_CellPhoneDB;Guide2Pharma_Cellinker;Guide2Pharma_LRdb;Guide2Pharma_talklr;ICELLNET;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;Wang;connectomeDB2020;iTALK;scConnect;talklr
3984 CellTalkDB;LRdb;Reactome_LRdb
3985 CellTalkDB;LRdb;Reactome_LRdb
3986 CellTalkDB;LRdb;Reactome_LRdb
3987 CellTalkDB;LRdb;Reactome_LRdb
3988 CellTalkDB;Fantom5_LRdb;LRdb;STRING_talklr;Wang;iTALK;talklr
3989 CellTalkDB;Fantom5_LRdb;LRdb;STRING_talklr;Wang;iTALK;talklr
3990 CellTalkDB;Wang
3991 CellTalkDB;Wang
3992 CellChatDB;CellPhoneDB;CellPhoneDB_Cellinker;Cellinker
3993 CellChatDB;CellPhoneDB;CellPhoneDB_Cellinker;Cellinker
3994 Baccin2019;CellTalkDB;Cellinker;Fantom5_LRdb;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;Wang;connectomeDB2020;iTALK;talklr
3995 Baccin2019;CellTalkDB;Cellinker;Fantom5_LRdb;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;Wang;connectomeDB2020;iTALK;talklr
3996 Baccin2019;CellTalkDB;Cellinker;Fantom5_LRdb;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;Wang;connectomeDB2020;iTALK;talklr
3997 Baccin2019;CellTalkDB;Cellinker;Fantom5_LRdb;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;Wang;connectomeDB2020;iTALK;talklr
3998 Baccin2019;CellTalkDB;Cellinker;Fantom5_LRdb;HPMR_Cellinker;HPMR_LRdb;HPMR_talklr;HPRD;HPRD_LRdb;HPRD_talklr;LRdb;Ramilowski2015;Ramilowski2015_Baccin2019;SIGNOR;Wang;connectomeDB2020;iTALK;talklr
     references
1    Baccin2019:1006133;Baccin2019:98194281;CellChatDB:22353464;CellPhoneDB:22353464;CellTalkDB:22353464;Cellinker:11006133;Cellinker:22353464;Cellinker:9819428;HPRD:11006133;ICELLNET:21685328;LRdb:11;LRdb:9819428;NetPath:11006133;SIGNOR:16140393;SPIKE:11006133;SPIKE:17537801;connectomeDB2020:11006133;connectomeDB2020:9819428
2    Baccin2019:10958687;BioGRID:9244302;CellChatDB:22353464;CellPhoneDB:22353464;CellTalkDB:10958687;Cellinker:10958687;Cellinker:22353464;HPRD:10958687;ICELLNET:21685328;LRdb:10958687;NetPath:10958687;SIGNOR:23111325;connectomeDB2020:10958687
3    CellChatDB:22353464;CellPhoneDB:22353464;CellTalkDB:22353464;Cellinker:22353464;Cellinker:29910816;connectomeDB2020:22353464
4    Baccin2019:11006133;Baccin2019:12482954;CancerCellMap:11006133;CellChatDB:22353464;CellPhoneDB:22353464;CellTalkDB:12482954;Cellinker:11006133;Cellinker:12482954;Cellinker:22353464;HPRD:11006133;HPRD:12482954;ICELLNET:21685328;LRdb:11;LRdb:12482954;NetPath:11006133;SIGNOR:11006133;connectomeDB2020:11006133;connectomeDB2020:12482954
5    Cellinker:9168114;Cellinker:9168115
6    Cellinker:9168114;Cellinker:9168115
7    CellTalkDB:23035126;Cellinker:23035126;IntAct:23091066;IntAct:26686862
8    CellTalkDB:19587294
9    CellTalkDB:22689693
10   CellTalkDB:21454673
11   CellTalkDB:18971959;SIGNOR:26284334
12   Baccin2019:16239146;CellTalkDB:16239146;HPRD:16239146;LRdb:16239146;connectomeDB2020:16239146
13   CellTalkDB:7822279;HPRD:16227584;HPRD:7822279;LRdb:7822279
14   ACSN:19601831;ACSN:19704010;ACSN:19726682;CellTalkDB:22399336;Cellinker:22399336;LRdb:22399336;SIGNOR:28624438
15   ACSN:19601831;ACSN:19704010;ACSN:19726682;CellTalkDB:24842903;SignaLink3:10423016;SignaLink3:23331499
16   CellTalkDB:30833305
17   CellTalkDB:23035126;Cellinker:23035126
18   CellTalkDB:28687716;Cellinker:23035126
19   CellTalkDB:28923481
20   Baccin2019:11733492;Baccin2019:12221720;Baccin2019:9520411;Baccin2019:9568710;CellTalkDB:11733492;Cellinker:11733492;Cellinker:12221720;Cellinker:9520411;Cellinker:9568710;HPMR:9568710;HPRD:12221720;HPRD:9520411;ICELLNET:11239407;IntAct:22664871;LRdb:11733492;LRdb:12221720;LRdb:9520411;LRdb:9568710;NetPath:14741739;NetPath:9568710;SIGNOR:11733492;connectomeDB2020:11733492;connectomeDB2020:12221720;connectomeDB2020:9520411;connectomeDB2020:9568710
21   CellTalkDB:27064449
22   Baccin2019:11581298;Baccin2019:9367155;CellTalkDB:11581298;Cellinker:11581298;Cellinker:9367155;HPMR:11581298;HPMR:15110169;HPRD:9367155;ICELLNET:11239407;IntAct:23333834;LRdb:11581298;LRdb:94;NetPath:14741739;NetPath:20483727;NetPath:9520411;SIGNOR:12897775;connectomeDB2020:11581298;connectomeDB2020:9367155
23   Cellinker:8626392;Cellinker:9419975
24   Cellinker:9419975
25   CellTalkDB:32196115;SIGNOR:16829981;SIGNOR:22891299
26   Adhesome:15242759;CellTalkDB:10944520;LRdb:10944520;connectomeDB2020:10944520
27   CellTalkDB:10944520;LRdb:10944520;connectomeDB2020:10944520
28   CellTalkDB:32196115
29   NetPath:17548657;connectomeDB2020:19473660
30   CellTalkDB:11094155;Cellinker:11094155;HPRD:11094155;LRdb:11094155;NetPath:11094155
⋮    ⋮
3969
3970
3971
3972
3973
3974 CellTalkDB:18195069;Cellinker:18195069;LRdb:18195069;Ramilowski2015:18195069;connectomeDB2020:18195069;talklr:18195069
3975 CellTalkDB:18195069;Cellinker:18195069;LRdb:18195069;Ramilowski2015:18195069;connectomeDB2020:18195069;talklr:18195069
3976 CellTalkDB:32196115
3977 CellTalkDB:32196115
3978 connectomeDB2020:20075072
3979 connectomeDB2020:20075072
3980 Baccin2019:10753626;CellTalkDB:10753626;Cellinker:10753626;HPRD:10753626;LRdb:10753626
3981 Baccin2019:10753626;CellTalkDB:10753626;Cellinker:10753626;HPRD:10753626;LRdb:10753626
3982 Baccin2019:9892621;CellChatDB:22610094;CellTalkDB:9892621;Cellinker:22610094;Cellinker:9892621;Guide2Pharma:9892621;ICELLNET:26130702;LRdb:9892621;connectomeDB2020:9892621;scConnect:9892621
3983 Baccin2019:9892621;CellChatDB:22610094;CellTalkDB:9892621;Cellinker:22610094;Cellinker:9892621;Guide2Pharma:9892621;ICELLNET:26130702;LRdb:9892621;connectomeDB2020:9892621;scConnect:9892621